services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: DB_NAME
      POSTGRES_USER: DB_USERNAME
      POSTGRES_PASSWORD: DB_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  springboot:
    image: myapp:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost/DB_NAME
      SPRING_DATASOURCE_USERNAME: DB_USERNAME
      SPRING_DATASOURCE_PASSWORD: DB_PASSWORD
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - maildev
    restart: always

volumes:
  postgres_data: