version: '3.8'

services:
  app:
    image: kashylt/trading-simulator:latest
    ports:
      - "8080:8080"
    volumes:
      - ./config/application.properties:/app/config/application.properties
    depends_on:
      - postgres
      - maildev

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: trading_simulator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  postgres_data: